name: Client CI

on:
  push:
    branches: [ main, master ]
    paths:
      - 'Client/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'Client/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: Client/package-lock.json
      - name: Install dependencies
        working-directory: ./Client
        run: npm ci
      - name: Build client
        working-directory: ./Client
        run: npm run build
      - name: Lint
        working-directory: ./Client
        run: npx eslint .
